{{- $name := .Values.postgres.secretName | default (printf "%s-postgres-credentials" .Release.Name) -}}
{{- $existing := lookup "v1" "Secret" .Values.namespace $name -}}
{{- $db := "" -}}
{{- $user := "" -}}
{{- $password := "" -}}

{{- if $existing }}
  {{- $db = index $existing.data "POSTGRES_DB" }}
  {{- $user = index $existing.data "POSTGRES_USER" }}
  {{- $password = index $existing.data "POSTGRES_PASSWORD" }}
{{- else }}
  {{- $db = b64enc (default "attendee_development" .Values.postgres.db) }}
  {{- $user = b64enc (default "attendee_development_user" .Values.postgres.user) }}
  {{- $password = b64enc (default "attendee_development_user" .Values.postgres.password) }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $name | quote }}
  namespace: {{ .Values.namespace | quote }}
  labels:
    app.kubernetes.io/name: postgres
type: Opaque
data:
  POSTGRES_DB: {{ $db | quote }}
  POSTGRES_USER: {{ $user | quote }}
  POSTGRES_PASSWORD: {{ $password | quote }}