# Generated by Django 5.1.14 on 2025-01-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0072_backfill_request_sync_for_all_calendars'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['start_time'], name='calendarevent_start_time_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['end_time'], name='calendarevent_end_time_idx'),
        ),
    ]
