# Generated by Django 5.1.14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0077_alter_participantevent_event_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediablob",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("audio/mp3", "MP3 Audio"),
                    ("image/png", "PNG Image"),
                    ("image/jpeg", "JPEG Image"),
                ],
                max_length=255,
            ),
        ),
    ]
