# Generated by Django 5.1.14 on 2026-05-04 15:52

from collections import defaultdict

from django.db import migrations


GOOGLE_MEET_PLATFORM = "google_meet"

NEW_GROUP_OBJECT_ID_PREFIX = "blg_"
NEW_LOGIN_OBJECT_ID_PREFIX = "bl_"


def _remap_object_id(legacy_object_id, new_prefix):
    # Reuse the random suffix from the legacy object_id so the new row is
    # trivially traceable back to the deprecated row it was migrated from.
    _, _, suffix = legacy_object_id.partition("_")
    return f"{new_prefix}{suffix}"


def populate_bot_login_groups_from_deprecated_models(apps, schema_editor):
    GoogleMeetBotLoginGroup = apps.get_model('bots', 'GoogleMeetBotLoginGroup')
    BotLoginGroup = apps.get_model('bots', 'BotLoginGroup')
    BotLogin = apps.get_model('bots', 'BotLogin')

    legacy_groups = GoogleMeetBotLoginGroup.objects.all().order_by('project_id', 'created_at', 'id')

    # The new (BotLoginGroup, BotLogin) tables are introduced in 0082, so they're
    # empty at this point. A simple per-project counter is enough to satisfy the
    # (project, platform, name) unique constraint.
    per_project_index = defaultdict(lambda: 1)

    for legacy_group in legacy_groups:
        project_id = legacy_group.project_id
        name = f"Login group {per_project_index[project_id]}"
        per_project_index[project_id] += 1

        new_group = BotLoginGroup.objects.create(
            project_id=project_id,
            object_id=_remap_object_id(legacy_group.object_id, NEW_GROUP_OBJECT_ID_PREFIX),
            platform=GOOGLE_MEET_PLATFORM,
            name=name,
        )

        for legacy_login in legacy_group.google_meet_bot_logins.all():
            BotLogin.objects.create(
                group=new_group,
                object_id=_remap_object_id(legacy_login.object_id, NEW_LOGIN_OBJECT_ID_PREFIX),
                _encrypted_data=legacy_login._encrypted_data,
                workspace_domain=legacy_login.workspace_domain,
                email=legacy_login.email,
                is_active=legacy_login.is_active,
                last_used_at=legacy_login.last_used_at,
            )


def reverse_populate_bot_login_groups_from_deprecated_models(apps, schema_editor):
    # No reverse operation - we don't want to delete created BotLoginGroups / BotLogins.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0082_botlogingroup_botlogin_and_more'),
    ]

    operations = [
        migrations.RunPython(
            populate_bot_login_groups_from_deprecated_models,
            reverse_populate_bot_login_groups_from_deprecated_models,
        ),
    ]
