{{- $name := .Values.minio.secretName | default "minio-credentials" -}}
{{- $existing := lookup "v1" "Secret" .Values.namespace $name -}}
{{- $access := "" -}}
{{- $secret := "" -}}

{{- if $existing }}
  {{- $access = index $existing.data "accesskey" }}
  {{- $secret = index $existing.data "secretkey" }}
{{- else }}
  {{- $access = b64enc "minioadmin" }}
  {{- $secret = randAlphaNum 32 | b64enc }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $name | quote }}
  namespace: {{ .Values.namespace | quote }}
  labels:
    app.kubernetes.io/name: minio
type: Opaque
data:
  accesskey: {{ $access | quote }}
  secretkey: {{ $secret | quote }}