apiVersion: apps/v1
kind: Deployment
metadata:
  name: attendee-worker
  labels:
    app: attendee-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attendee-worker
  template:
    metadata:
      labels:
        app: attendee-worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.attendee.image }}"
          command: ["celery", "-A", "attendee", "worker", "-l", "INFO"]
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "attendee.settings.production"
            - name: POSTGRES_HOST
              value: "postgres"
            - name: REDIS_URL
              value: "{{ .Values.redis.url }}"
          envFrom:
            - secretRef:
                name: attendee-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"