apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: {{ .Values.namespace | quote }}
  labels:
    app: minio
spec:
  selector:
    app: minio
  ports:
    - name: api
      port: {{ .Values.minio.service.port }}
      targetPort: {{ .Values.minio.service.port }}
    - name: console
      port: {{ .Values.minio.service.consolePort }}
      targetPort: {{ .Values.minio.service.consolePort }}
  type: ClusterIP