apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: {{ .Values.namespace | quote }}
  labels:
    app: minio
spec:
  serviceName: minio
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: {{ .Values.minio.image | quote }}
          imagePullPolicy: {{ .Values.minio.imagePullPolicy }}
          args:
            - "server"
            - "/data"
            - "--console-address"
            - ":{{ .Values.minio.service.consolePort }}"
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.minio.secretName | default "minio-credentials" | quote }}
                  key: accesskey
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.minio.secretName | default "minio-credentials" | quote }}
                  key: secretkey
          ports:
            - containerPort: {{ .Values.minio.service.port }}
              name: api
            - containerPort: {{ .Values.minio.service.consolePort }}
              name: console
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.minio.persistence.size }}