{{- $name := printf "%s-%s-%s-attendee" .Values.customer.customercode .Values.namingConvention.secret.shortcode .Values.namingConvention.frontend.pgadmin }}
{{- $existing := lookup "v1" "Secret" .Values.customer.namespace $name }}
{{- $defaultEmail := .Values.pgadmin.email | default "admin@revodata.nl" }}
{{- $email := "" }}
{{- $password := "" }}

{{- if $existing }}
  {{- $email = index $existing.data "PGADMIN_DEFAULT_EMAIL" }}
  {{- $password = index $existing.data "PGADMIN_DEFAULT_PASSWORD" }}
{{- else }}
  {{- $email = b64enc $defaultEmail }}
  {{- $password = randAlphaNum 16 | b64enc }}
{{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name | quote }}
  namespace: {{ .Values.customer.namespace | quote }}
  labels:
    app.kubernetes.io/name: pgadmin
type: Opaque
data:
  PGADMIN_DEFAULT_EMAIL: {{ $email | quote }}
  PGADMIN_DEFAULT_PASSWORD: {{ $password | quote }}